# DAML 02 - NumPy Exercises - Solutions

Michal Grochmal <michal.grochmal@city.ac.uk>

Exercises rating:

★☆☆ - You should be able to do it based on Python knowledge plus lecture contents.

★★☆ - You will need to do extra thinking and some extra reading/searching.

★★★ - The answer is difficult to find by a simple search,
      requires you to do a considerable amount of extra work by yourself
      (feel free to ignore these exercises if you're short on time).

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np
np

<module 'numpy' from '/home/grochmal/anaconda3/lib/python3.6/site-packages/numpy/__init__.py'>

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__config__.show()
np.__version__

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/grochmal/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/grochmal/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/grochmal/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/grochmal/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/grochmal/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/grochmal/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/grochmal/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/grochmal/anaconda3/include']


'1.13.3'

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [4]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [5]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 6. Create a 3x3x3 array with random values (★☆☆)

In [6]:
np.random.rand(3, 3, 3)

array([[[ 0.8839346 ,  0.52971844,  0.42800008],
        [ 0.06869912,  0.64076383,  0.34922454],
        [ 0.8309267 ,  0.88516498,  0.35498562]],

       [[ 0.19182745,  0.48045924,  0.98679375],
        [ 0.09597152,  0.05321238,  0.59446448],
        [ 0.59183753,  0.56290569,  0.36031575]],

       [[ 0.59112359,  0.85777523,  0.28274019],
        [ 0.74677047,  0.14413123,  0.71532327],
        [ 0.46204791,  0.86041549,  0.93993973]]])

#### 7. Sort the columns of the following array (★☆☆)

In [7]:
x = np.array([[3, 7],
              [7, 3],
              [1, 2]])
x.sort(axis=0)
x

array([[1, 2],
       [3, 3],
       [7, 7]])

#### 8. Select the 3rd, 4th and 7th column of the following array (★★☆)

In [8]:
x = np.arange(32).reshape(4, 8)
x[:, [2, 3, 6]]

array([[ 2,  3,  6],
       [10, 11, 14],
       [18, 19, 22],
       [26, 27, 30]])

#### 9. Use `argsort` to sort the following array (★★☆)

In [9]:
x = np.array([2, 7, 42, 27, 6, 9, 12])
x[x.argsort()]

array([ 2,  6,  7,  9, 12, 27, 42])

#### 10. Retrieve all positive values smaller than 7 (★★☆)

In [10]:
x = np.arange(-6, 58, 2).reshape(4, 8)
x[(x > 0) & (x < 7)]

array([2, 4, 6])

#### 11. In a single operation add 2 to all odd columns and 7 to all even columns (★★☆)

In [11]:
x = np.arange(32).reshape(4, 8)
x + np.array([2, 7]*x.shape[0])

array([[ 2,  8,  4, 10,  6, 12,  8, 14],
       [10, 16, 12, 18, 14, 20, 16, 22],
       [18, 24, 20, 26, 22, 28, 24, 30],
       [26, 32, 28, 34, 30, 36, 32, 38]])